DATA FUELDAT;
INFILE 'E:\HW3\fuel.txt' firstobs=2;
INPUT CS ST $ POP TAX NLIC INC ROAD FUELC;
DLIC = 100* (NLIC/POP);
FUEL = 1000* (FUELC/POP);
RUN;

PROC REG DATA=FUELDAT;

MODEL FUEL = TAX DLIC INC/ R INFLUENCE;
RUN;

DATA FUELDAT2;
INFILE 'E:\HW3\fuel.txt' firstobs=2;
INPUT CS ST $ POP TAX NLIC INC ROAD FUELC;
DLIC = 100* (NLIC/POP);
FUEL = 1000* (FUELC/POP);
if cs=50 then delete;
RUN;

PROC REG DATA=FUELDAT2;

MODEL FUEL = TAX DLIC INC/ R INFLUENCE;
RUN;
